"use client";

import React, { useState } from "react";
import { Copy, Check, Download, FileText, Mail, Linkedin, AlertTriangle, Lightbulb, Star, ChevronDown } from "lucide-react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

// ─────────────────────────────────────────────
// PDF Styles
// ─────────────────────────────────────────────
const docStyles = StyleSheet.create({
    page: { fontFamily: "Times-Roman", fontSize: 11.5, color: "#111", padding: "56 60", lineHeight: 1.65, background: "#fff" },
    heading: { fontSize: 10, fontFamily: "Times-Bold", textTransform: "uppercase", letterSpacing: 1.5, color: "#4338ca", borderBottom: "1pt solid #c7d2fe", paddingBottom: 4, marginBottom: 10, marginTop: 0 },
    body: { fontSize: 11, lineHeight: 1.7, color: "#333" },
    label: { fontFamily: "Times-Bold", fontSize: 10, color: "#888", textTransform: "uppercase", letterSpacing: 1.5, marginBottom: 4, marginTop: 14 },
    small: { fontSize: 9.5, color: "#777" },
    contact: { fontSize: 10, color: "#555", marginBottom: 2 },
    footer: { position: "absolute", bottom: 30, left: 60, right: 60, fontSize: 9, color: "#bbb", textAlign: "center", borderTop: "0.5pt solid #eee", paddingTop: 6 },
});

function buildDocPDF(title: string, content: string, candidateName?: string) {
    const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const paragraphs = content.split("\n\n").filter(Boolean);
    return (
        <Document title={title}>
            <Page size="A4" style={docStyles.page}>
                {candidateName && <Text style={{ fontFamily: "Times-Bold", fontSize: 17, marginBottom: 4 }}>{candidateName}</Text>}
                <Text style={{ fontSize: 9.5, color: "#888", marginBottom: 20 }}>{date}</Text>
                <Text style={docStyles.heading}>{title}</Text>
                {paragraphs.map((para, i) => (
                    <Text key={i} style={{ ...docStyles.body, marginBottom: 10 }}>{para.trim()}</Text>
                ))}
                <Text style={docStyles.footer}>Generated by AI CV Optimizer · {date}</Text>
            </Page>
        </Document>
    );
}

async function downloadDocPDF(title: string, content: string, candidateName?: string) {
    const { pdf } = await import("@react-pdf/renderer");
    const doc = buildDocPDF(title, content, candidateName);
    const blob = await pdf(doc as any).toBlob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "_")}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ─────────────────────────────────────────────
// CopyButton
// ─────────────────────────────────────────────
function CopyButton({ text }: { text: string }) {
    const [copied, setCopied] = useState(false);
    const handle = async () => {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };
    return (
        <button onClick={handle} className="flex items-center gap-1.5 text-xs font-bold text-neutral-500 hover:text-indigo-600 transition-colors px-2 py-1 rounded-lg hover:bg-indigo-50 dark:hover:bg-indigo-900/20">
            {copied ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? "Copied!" : "Copy"}
        </button>
    );
}

// ─────────────────────────────────────────────
// PdfButton
// ─────────────────────────────────────────────
function PdfButton({ title, content, name }: { title: string; content: string; name?: string }) {
    const [loading, setLoading] = useState(false);
    const handle = async () => {
        setLoading(true);
        try { await downloadDocPDF(title, content, name); }
        finally { setLoading(false); }
    };
    return (
        <button onClick={handle} disabled={loading}
            className="flex items-center gap-1.5 text-xs font-bold bg-indigo-600 text-white hover:bg-indigo-700 transition px-3 py-1.5 rounded-lg disabled:opacity-60">
            <Download className="w-3.5 h-3.5" />
            {loading ? "Generating…" : "PDF"}
        </button>
    );
}

// ─────────────────────────────────────────────
// Text Block (formatted paragraph display)
// ─────────────────────────────────────────────
function DocBlock({ content }: { content: string }) {
    if (!content) return <p className="text-neutral-400 italic text-sm">No content generated.</p>;
    return (
        <div className="space-y-4">
            {content.split("\n\n").filter(Boolean).map((para, i) => (
                <p key={i} className="text-sm text-neutral-700 dark:text-neutral-300 leading-relaxed">{para.trim()}</p>
            ))}
        </div>
    );
}

// ─────────────────────────────────────────────
// ATS Score Badge
// ─────────────────────────────────────────────
function AtsScore({ score }: { score?: number }) {
    if (!score) return null;
    const color = score >= 80 ? "text-green-600" : score >= 60 ? "text-amber-500" : "text-red-500";
    const bg = score >= 80 ? "bg-green-50 border-green-200" : score >= 60 ? "bg-amber-50 border-amber-200" : "bg-red-50 border-red-200";
    return (
        <div className={`inline-flex items-center gap-3 px-4 py-2.5 rounded-2xl border ${bg} mb-6`}>
            <div className="relative w-12 h-12">
                <svg className="w-12 h-12 -rotate-90" viewBox="0 0 36 36">
                    <circle cx="18" cy="18" r="15.9" fill="none" stroke="#e5e7eb" strokeWidth="3" />
                    <circle cx="18" cy="18" r="15.9" fill="none"
                        stroke={score >= 80 ? "#16a34a" : score >= 60 ? "#d97706" : "#dc2626"}
                        strokeWidth="3" strokeDasharray={`${score} 100`} strokeLinecap="round" />
                </svg>
                <span className={`absolute inset-0 flex items-center justify-center text-xs font-black ${color}`}>{score}</span>
            </div>
            <div>
                <p className={`text-base font-black ${color}`}>ATS Score: {score}/100</p>
                <p className="text-xs text-neutral-500">{score >= 80 ? "Excellent match" : score >= 60 ? "Good — minor gaps" : "Needs improvement"}</p>
            </div>
        </div>
    );
}

// ─────────────────────────────────────────────
// Main ResultsTabs
// ─────────────────────────────────────────────
export function ResultsTabs({ parsedOutput }: { parsedOutput: any }) {
    const [activeTab, setActiveTab] = useState("cover");

    if (!parsedOutput) return null;

    const out = parsedOutput;
    const name = out.tailored_resume_json?.header?.fullName || out.tailored_resume_json?.basicInfo?.fullName || "";

    const tabs = [
        { id: "cover", label: "Cover Letter", icon: FileText },
        { id: "motivation", label: "Motivation", icon: Star },
        { id: "email", label: "Email", icon: Mail },
        { id: "linkedin", label: "LinkedIn", icon: Linkedin },
        { id: "gaps", label: "Gaps & Tips", icon: AlertTriangle },
    ];

    const activeContent = {
        cover: out.cover_letter || "",
        motivation: out.motivation_letter || "",
        email: out.application_text || "",
        linkedin: [out.linkedin_messages?.recruiter, out.linkedin_messages?.hiring_manager, out.linkedin_messages?.referral].filter(Boolean).join("\n\n-----\n\n"),
    } as Record<string, string>;

    const tabTitles: Record<string, string> = {
        cover: "Cover Letter",
        motivation: "Motivation Letter",
        email: "Application Email",
        linkedin: "LinkedIn Messages",
    };

    return (
        <div className="bg-white/70 dark:bg-black/50 backdrop-blur-2xl border border-neutral-200 dark:border-neutral-800 rounded-3xl overflow-hidden shadow-xl shadow-black/5">
            {/* ATS Score banner */}
            {out.ats_score && (
                <div className="px-6 pt-5">
                    <AtsScore score={out.ats_score} />
                </div>
            )}

            {/* Tabs */}
            <div className="flex overflow-x-auto px-4 pt-2 gap-1 border-b border-neutral-100 dark:border-neutral-800">
                {tabs.map(tab => {
                    const Icon = tab.icon;
                    return (
                        <button key={tab.id} onClick={() => setActiveTab(tab.id)}
                            className={`flex items-center gap-1.5 px-3 py-2.5 text-xs font-bold whitespace-nowrap rounded-t-xl transition-all border-b-2 ${activeTab === tab.id
                                ? "border-indigo-500 text-indigo-600 dark:text-indigo-400 bg-indigo-50/60 dark:bg-indigo-900/25"
                                : "border-transparent text-neutral-500 hover:text-neutral-800 dark:hover:text-neutral-200"}`}>
                            <Icon className="w-3.5 h-3.5" />
                            {tab.label}
                        </button>
                    );
                })}
            </div>

            {/* Content */}
            <div className="p-6" key={activeTab}>
                {activeTab !== "gaps" ? (
                    <>
                        {/* Action bar */}
                        <div className="flex items-center justify-between mb-4">
                            <p className="text-xs font-bold text-neutral-400 uppercase tracking-wider">{tabTitles[activeTab]}</p>
                            <div className="flex items-center gap-2">
                                <CopyButton text={activeContent[activeTab]} />
                                <PdfButton title={tabTitles[activeTab]} content={activeContent[activeTab]} name={name} />
                            </div>
                        </div>

                        {activeTab === "linkedin" ? (
                            <div className="space-y-4">
                                {[
                                    { label: "To Recruiter", content: out.linkedin_messages?.recruiter },
                                    { label: "To Hiring Manager", content: out.linkedin_messages?.hiring_manager },
                                    { label: "Referral Request", content: out.linkedin_messages?.referral },
                                ].map((msg, i) => (
                                    <div key={i} className="p-4 bg-neutral-50 dark:bg-neutral-900 rounded-2xl border border-neutral-100 dark:border-neutral-800">
                                        <div className="flex items-center justify-between mb-2">
                                            <span className="text-[10px] font-black uppercase tracking-widest text-indigo-500">{msg.label}</span>
                                            <CopyButton text={msg.content || ""} />
                                        </div>
                                        <p className="text-sm text-neutral-700 dark:text-neutral-300 leading-relaxed">{msg.content}</p>
                                    </div>
                                ))}
                            </div>
                        ) : (
                            <div className="bg-neutral-50 dark:bg-neutral-900 rounded-2xl border border-neutral-100 dark:border-neutral-800 p-5 max-h-[540px] overflow-y-auto">
                                <DocBlock content={activeContent[activeTab]} />
                            </div>
                        )}
                    </>
                ) : (
                    /* Gaps & Tips */
                    <div className="space-y-6">
                        {/* Keywords used */}
                        {out.ats_keywords_used?.length > 0 && (
                            <div>
                                <p className="text-xs font-black uppercase tracking-widest text-green-600 mb-3">✅ ATS Keywords Matched</p>
                                <div className="flex flex-wrap gap-2">
                                    {out.ats_keywords_used.map((kw: string, i: number) => (
                                        <span key={i} className="px-3 py-1 bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-400 text-xs font-semibold rounded-full border border-green-200 dark:border-green-700">{kw}</span>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Missing requirements */}
                        {out.missing_requirements?.length > 0 && (
                            <div>
                                <p className="text-xs font-black uppercase tracking-widest text-red-500 mb-3">⚠️ Missing Requirements</p>
                                <ul className="space-y-2">
                                    {out.missing_requirements.map((r: string, i: number) => (
                                        <li key={i} className="flex items-start gap-2 text-sm text-neutral-700 dark:text-neutral-300">
                                            <AlertTriangle className="w-4 h-4 text-red-400 mt-0.5 flex-shrink-0" />
                                            {r}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        )}

                        {/* Suggestions */}
                        {out.suggestions && (
                            <div className="grid sm:grid-cols-2 gap-4">
                                {[
                                    { key: "courses", label: "📚 Recommended Courses", color: "blue" },
                                    { key: "skills_to_learn", label: "🛠 Skills to Learn", color: "purple" },
                                    { key: "projects", label: "💡 Project Ideas", color: "amber" },
                                ].map(({ key, label, color }) =>
                                    out.suggestions[key]?.length > 0 ? (
                                        <div key={key} className={`p-4 bg-${color}-50 dark:bg-${color}-900/10 border border-${color}-100 dark:border-${color}-800/30 rounded-2xl`}>
                                            <p className="text-xs font-black uppercase tracking-widest text-neutral-500 mb-2">{label}</p>
                                            <ul className="space-y-1.5">
                                                {out.suggestions[key].map((item: string, i: number) => (
                                                    <li key={i} className="text-sm text-neutral-700 dark:text-neutral-300 flex items-start gap-2">
                                                        <span className="mt-1 text-neutral-400">•</span>{item}
                                                    </li>
                                                ))}
                                            </ul>
                                        </div>
                                    ) : null
                                )}
                            </div>
                        )}

                        {/* Career tip */}
                        {out.suggestions?.career_tip && (
                            <div className="p-4 bg-gradient-to-r from-indigo-50 to-purple-50 dark:from-indigo-900/20 dark:to-purple-900/20 border border-indigo-200 dark:border-indigo-700/50 rounded-2xl flex gap-3">
                                <Lightbulb className="w-5 h-5 text-indigo-500 flex-shrink-0 mt-0.5" />
                                <div>
                                    <p className="text-xs font-black uppercase tracking-widest text-indigo-600 mb-1">💼 Strategic Career Tip</p>
                                    <p className="text-sm text-neutral-700 dark:text-neutral-300 leading-relaxed">{out.suggestions.career_tip}</p>
                                </div>
                            </div>
                        )}
                    </div>
                )}
            </div>

            {/* All Documents PDF bundle */}
            <div className="border-t border-neutral-100 dark:border-neutral-800 px-6 py-4 bg-neutral-50/50 dark:bg-neutral-900/30">
                <div className="flex items-center justify-between flex-wrap gap-3">
                    <p className="text-xs font-bold text-neutral-400">Download all documents as PDF</p>
                    <div className="flex gap-2 flex-wrap">
                        {out.cover_letter && <PdfButton title="Cover_Letter" content={out.cover_letter} name={name} />}
                        {out.motivation_letter && <PdfButton title="Motivation_Letter" content={out.motivation_letter} name={name} />}
                        {out.application_text && <PdfButton title="Application_Email" content={out.application_text} name={name} />}
                    </div>
                </div>
            </div>
        </div>
    );
}
