"use client";

import React, { useState } from "react";
import { Copy, Check, Download, FileText, Mail, Linkedin, AlertTriangle, Lightbulb, Star, Target, BookOpen, Briefcase, ExternalLink } from "lucide-react";

// ─────────────────────────────────────────────
// CopyButton
// ─────────────────────────────────────────────
function CopyButton({ text, label = "Copy" }: { text: string; label?: string }) {
    const [copied, setCopied] = useState(false);
    const handle = async () => {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };
    return (
        <button onClick={handle}
            className="flex items-center gap-1.5 text-sm font-bold text-neutral-500 hover:text-indigo-600 transition-colors px-3 py-1.5 rounded-xl hover:bg-indigo-50 dark:hover:bg-indigo-900/20 border border-neutral-200 dark:border-neutral-700">
            {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied!" : label}
        </button>
    );
}

// ─────────────────────────────────────────────
// PdfButton — generates PDF from letter content
// ─────────────────────────────────────────────
function PdfButton({ title, content, name }: { title: string; content: string; name?: string }) {
    const [loading, setLoading] = useState(false);
    const handle = async () => {
        if (!content) return;
        setLoading(true);
        try {
            const { pdf, Document, Page, Text, View, StyleSheet } = await import("@react-pdf/renderer");
            const styles = StyleSheet.create({
                page: { fontFamily: "Times-Roman", fontSize: 11, color: "#111", padding: "52 58", lineHeight: 1.7, backgroundColor: "#fff" },
                heading: { fontSize: 16, fontFamily: "Times-Bold", marginBottom: 4 },
                date: { fontSize: 9.5, color: "#888", marginBottom: 22 },
                title: { fontSize: 10, fontFamily: "Times-Bold", textTransform: "uppercase", letterSpacing: 1.5, color: "#4338ca", borderBottom: "1pt solid #c7d2fe", paddingBottom: 4, marginBottom: 14 },
                para: { fontSize: 11, lineHeight: 1.72, color: "#1a1a1a", marginBottom: 12 },
                footer: { position: "absolute", bottom: 28, left: 58, right: 58, fontSize: 8.5, color: "#bbb", textAlign: "center", borderTop: "0.5pt solid #eee", paddingTop: 5 },
            });
            const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
            const doc = (
                <Document title={title}>
                    <Page size="A4" style={styles.page}>
                        {name && <Text style={styles.heading}>{name}</Text>}
                        <Text style={styles.date}>{date}</Text>
                        <Text style={styles.title}>{title}</Text>
                        {content.split("\n\n").filter(Boolean).map((p, i) => (
                            <Text key={i} style={styles.para}>{p.trim()}</Text>
                        ))}
                        <Text style={styles.footer}>Generated by AI CV Optimizer · {date}</Text>
                    </Page>
                </Document>
            );
            const blob = await pdf(doc as any).toBlob();
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `${title.replace(/\s+/g, "_")}.pdf`;
            document.body.appendChild(a); a.click(); document.body.removeChild(a);
            setTimeout(() => URL.revokeObjectURL(url), 1000);
        } finally { setLoading(false); }
    };
    return (
        <button onClick={handle} disabled={loading || !content}
            className="flex items-center gap-1.5 text-sm font-bold bg-indigo-600 text-white hover:bg-indigo-700 transition px-3 py-1.5 rounded-xl disabled:opacity-50">
            <Download className="w-4 h-4" />
            {loading ? "Generating…" : "PDF"}
        </button>
    );
}

// ─────────────────────────────────────────────
// ATS Score — large, readable
// ─────────────────────────────────────────────
function AtsScore({ score, explanation }: { score?: number; explanation?: string }) {
    if (score == null) return null;
    const pct = Math.min(100, Math.max(0, score));
    const color = pct >= 80 ? "#16a34a" : pct >= 60 ? "#d97706" : "#dc2626";
    const bgClass = pct >= 80
        ? "bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800"
        : pct >= 60
            ? "bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800"
            : "bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800";
    const label = pct >= 80 ? "Excellent match" : pct >= 60 ? "Good — minor gaps remain" : "Needs improvement";

    return (
        <div className={`p-5 rounded-2xl border-2 ${bgClass} mb-5`}>
            <div className="flex items-center gap-5">
                {/* Big circular score */}
                <div className="relative w-20 h-20 flex-shrink-0">
                    <svg className="w-20 h-20 -rotate-90" viewBox="0 0 36 36">
                        <circle cx="18" cy="18" r="15.9" fill="none" stroke="#e5e7eb" strokeWidth="3" />
                        <circle cx="18" cy="18" r="15.9" fill="none"
                            stroke={color} strokeWidth="3.5"
                            strokeDasharray={`${pct} 100`} strokeLinecap="round" />
                    </svg>
                    <span className="absolute inset-0 flex items-center justify-center text-2xl font-black" style={{ color }}>{pct}</span>
                </div>
                <div>
                    <p className="text-2xl font-black" style={{ color }}>ATS Score: {pct}/100</p>
                    <p className="text-neutral-500 dark:text-neutral-400 font-medium mt-0.5">{label}</p>
                </div>
            </div>
            {/* Score explanation */}
            {explanation && (
                <div className="mt-4 pt-4 border-t border-neutral-200/50 dark:border-neutral-700/50">
                    <p className="text-xs font-black uppercase tracking-widest text-neutral-400 mb-1.5">Why this score?</p>
                    <p className="text-sm text-neutral-700 dark:text-neutral-300 leading-relaxed">{explanation}</p>
                </div>
            )}
        </div>
    );
}


// ─────────────────────────────────────────────
// DocBlock — properly formatted letter
// ─────────────────────────────────────────────
function DocBlock({ content }: { content: string }) {
    if (!content) return <p className="text-neutral-400 italic">No content generated.</p>;
    return (
        <div className="space-y-5">
            {content.split("\n\n").filter(s => s.trim()).map((para, i) => (
                <p key={i} className="text-[15px] text-neutral-800 dark:text-neutral-200 leading-[1.85] tracking-[0.01em]">
                    {para.trim()}
                </p>
            ))}
        </div>
    );
}

// ─────────────────────────────────────────────
// Main ResultsTabs
// ─────────────────────────────────────────────
export function ResultsTabs({ parsedOutput, cvData, templateId }: {
    parsedOutput: any;
    cvData?: any;
    templateId?: string;
}) {
    const [activeTab, setActiveTab] = useState("cover");

    if (!parsedOutput) return null;
    const out = parsedOutput;
    const name = out.tailored_resume_json?.basicInfo?.fullName || out.tailored_resume_json?.header?.fullName || "";

    const tabs = [
        { id: "cover", label: "Cover Letter", icon: FileText },
        { id: "motivation", label: "Motivation", icon: Star },
        { id: "email", label: "Email", icon: Mail },
        { id: "linkedin", label: "LinkedIn", icon: Linkedin },
        { id: "gaps", label: "Gaps & Tips", icon: AlertTriangle },
    ];


    const contentMap: Record<string, string> = {
        cover: out.cover_letter || "",
        motivation: out.motivation_letter || "",
        email: out.application_text || "",
        linkedin: [out.linkedin_messages?.recruiter, out.linkedin_messages?.hiring_manager, out.linkedin_messages?.referral].filter(Boolean).join("\n\n-----\n\n"),
    };

    const titleMap: Record<string, string> = {
        cover: "Cover Letter",
        motivation: "Motivation Letter",
        email: "Application Email",
        linkedin: "LinkedIn Messages",
    };

    // Extract job title from tailored CV summary or skills for job search
    const jobTitle = name
        ? (out.tailored_resume_json?.experience?.[0]?.role || "")
        : "";

    return (
        <div className="bg-white/80 dark:bg-neutral-950/80 backdrop-blur-2xl border border-neutral-200 dark:border-neutral-800 rounded-3xl overflow-hidden shadow-2xl shadow-black/10">

            {/* ATS Score */}
            <div className="px-6 pt-6">
                <AtsScore score={out.ats_score} explanation={out.ats_score_explanation} />
            </div>


            {/* Tabs */}
            <div className="flex overflow-x-auto px-4 pt-1 gap-0.5 border-b border-neutral-200 dark:border-neutral-800">
                {tabs.map(tab => {
                    const Icon = tab.icon;
                    const isActive = activeTab === tab.id;
                    return (
                        <button key={tab.id} onClick={() => setActiveTab(tab.id)}
                            className={`flex items-center gap-1.5 px-4 py-3 text-sm font-bold whitespace-nowrap border-b-2 transition-all ${isActive
                                ? "border-indigo-500 text-indigo-600 dark:text-indigo-400 bg-indigo-50/60 dark:bg-indigo-900/20"
                                : "border-transparent text-neutral-500 hover:text-neutral-800 dark:hover:text-neutral-200 hover:border-neutral-300"}`}>
                            <Icon className="w-4 h-4" />
                            {tab.label}
                        </button>
                    );
                })}
            </div>

            {/* Content area */}
            <div className="p-6" key={activeTab}>

                {/* Letter tabs */}
                {["cover", "motivation", "email"].includes(activeTab) && (
                    <>
                        <div className="flex items-center justify-between mb-5 pb-4 border-b border-neutral-100 dark:border-neutral-800">
                            <h3 className="text-lg font-black text-neutral-900 dark:text-white">{titleMap[activeTab]}</h3>
                            <div className="flex items-center gap-2">
                                <CopyButton text={contentMap[activeTab]} label="Copy Text" />
                                <PdfButton title={titleMap[activeTab]} content={contentMap[activeTab]} name={name} />
                            </div>
                        </div>
                        <div className="bg-neutral-50 dark:bg-neutral-900 rounded-2xl border border-neutral-200 dark:border-neutral-800 p-6 max-h-[600px] overflow-y-auto">
                            <DocBlock content={contentMap[activeTab]} />
                        </div>
                    </>
                )}

                {/* LinkedIn tab */}
                {activeTab === "linkedin" && (
                    <div className="space-y-4">
                        <div className="flex items-center justify-between mb-1">
                            <h3 className="text-lg font-black text-neutral-900 dark:text-white">LinkedIn Messages</h3>
                            <PdfButton title="LinkedIn Messages" content={contentMap.linkedin} name={name} />
                        </div>
                        {[
                            { label: "💼 To Recruiter", sublabel: "Connection request (max 300 chars)", content: out.linkedin_messages?.recruiter },
                            { label: "👔 To Hiring Manager", sublabel: "Direct InMail", content: out.linkedin_messages?.hiring_manager },
                            { label: "🤝 Referral Request", sublabel: "To a mutual connection", content: out.linkedin_messages?.referral },
                        ].map((msg, i) => (
                            <div key={i} className="p-5 bg-neutral-50 dark:bg-neutral-900 rounded-2xl border border-neutral-200 dark:border-neutral-800">
                                <div className="flex items-start justify-between mb-3">
                                    <div>
                                        <p className="font-black text-neutral-900 dark:text-white">{msg.label}</p>
                                        <p className="text-xs text-neutral-400 mt-0.5">{msg.sublabel}</p>
                                    </div>
                                    <CopyButton text={msg.content || ""} />
                                </div>
                                <p className="text-[15px] text-neutral-800 dark:text-neutral-200 leading-relaxed">{msg.content}</p>
                                {msg.content && <p className="text-xs text-neutral-400 mt-2 text-right">{msg.content.length} chars</p>}
                            </div>
                        ))}
                    </div>
                )}

                {/* Gaps & Tips */}
                {activeTab === "gaps" && (
                    <div className="space-y-6">
                        {/* ATS keywords matched */}
                        {out.ats_keywords_used?.length > 0 && (
                            <div>
                                <p className="text-sm font-black uppercase tracking-widest text-green-600 dark:text-green-400 mb-3 flex items-center gap-2">
                                    <span className="text-base">✅</span> ATS Keywords Matched ({out.ats_keywords_used.length})
                                </p>
                                <div className="flex flex-wrap gap-2">
                                    {out.ats_keywords_used.map((kw: string, i: number) => (
                                        <span key={i} className="px-3 py-1.5 bg-green-50 dark:bg-green-900/20 text-green-800 dark:text-green-300 text-sm font-semibold rounded-full border border-green-200 dark:border-green-800">
                                            {kw}
                                        </span>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Missing requirements with improvement links */}
                        {out.missing_requirements?.length > 0 && (
                            <div>
                                <p className="text-sm font-black uppercase tracking-widest text-red-500 mb-3 flex items-center gap-2">
                                    <span className="text-base">⚠️</span> Gaps — What the JD requires that you may lack
                                </p>
                                <div className="space-y-3">
                                    {out.missing_requirements.map((r: string, i: number) => {
                                        const searchQ = encodeURIComponent(r.replace(/^JD requires\s*/i, "").slice(0, 80));
                                        return (
                                            <div key={i} className="p-4 bg-red-50 dark:bg-red-900/10 rounded-xl border border-red-100 dark:border-red-900/30">
                                                <div className="flex items-start gap-3">
                                                    <AlertTriangle className="w-4 h-4 text-red-400 mt-0.5 flex-shrink-0" />
                                                    <p className="text-sm text-neutral-800 dark:text-neutral-200 leading-relaxed">{r}</p>
                                                </div>
                                                <div className="flex gap-2 mt-3 ml-7 flex-wrap">
                                                    <a href={`https://www.udemy.com/courses/search/?q=${searchQ}`} target="_blank" rel="noopener noreferrer"
                                                        className="text-xs font-bold px-3 py-1.5 bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 rounded-full hover:bg-purple-200 dark:hover:bg-purple-900/50 transition flex items-center gap-1">
                                                        🎓 Udemy
                                                    </a>
                                                    <a href={`https://www.youtube.com/results?search_query=${searchQ}+tutorial`} target="_blank" rel="noopener noreferrer"
                                                        className="text-xs font-bold px-3 py-1.5 bg-red-100 dark:bg-red-900/20 text-red-700 dark:text-red-300 rounded-full hover:bg-red-200 dark:hover:bg-red-900/40 transition flex items-center gap-1">
                                                        ▶ YouTube
                                                    </a>
                                                    <a href={`https://www.coursera.org/search?query=${searchQ}`} target="_blank" rel="noopener noreferrer"
                                                        className="text-xs font-bold px-3 py-1.5 bg-blue-100 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 rounded-full hover:bg-blue-200 dark:hover:bg-blue-900/40 transition flex items-center gap-1">
                                                        📘 Coursera
                                                    </a>
                                                    <a href={`https://www.google.com/search?q=how+to+learn+${searchQ}`} target="_blank" rel="noopener noreferrer"
                                                        className="text-xs font-bold px-3 py-1.5 bg-neutral-100 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-300 rounded-full hover:bg-neutral-200 dark:hover:bg-neutral-700 transition flex items-center gap-1">
                                                        🔍 Google
                                                    </a>
                                                </div>
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>
                        )}


                        {/* Suggestions grid */}
                        {out.suggestions && (
                            <div className="space-y-4">
                                {out.suggestions.courses?.length > 0 && (
                                    <div className="p-5 bg-blue-50 dark:bg-blue-900/10 border border-blue-100 dark:border-blue-800/30 rounded-2xl">
                                        <p className="text-sm font-black uppercase tracking-widest text-blue-700 dark:text-blue-400 mb-3 flex items-center gap-2">
                                            <BookOpen className="w-4 h-4" /> Recommended Courses
                                        </p>
                                        <ul className="space-y-2">
                                            {out.suggestions.courses.map((item: string, i: number) => (
                                                <li key={i} className="flex items-start gap-2 text-sm text-neutral-800 dark:text-neutral-200">
                                                    <span className="text-blue-400 mt-1 flex-shrink-0">•</span>{item}
                                                </li>
                                            ))}
                                        </ul>
                                    </div>
                                )}
                                {out.suggestions.skills_to_learn?.length > 0 && (
                                    <div className="p-5 bg-purple-50 dark:bg-purple-900/10 border border-purple-100 dark:border-purple-800/30 rounded-2xl">
                                        <p className="text-sm font-black uppercase tracking-widest text-purple-700 dark:text-purple-400 mb-3 flex items-center gap-2">
                                            <Target className="w-4 h-4" /> Skills to Learn
                                        </p>
                                        <div className="flex flex-wrap gap-2">
                                            {out.suggestions.skills_to_learn.map((sk: string, i: number) => (
                                                <span key={i} className="px-3 py-1.5 bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-300 text-sm font-semibold rounded-full">
                                                    {sk}
                                                </span>
                                            ))}
                                        </div>
                                    </div>
                                )}
                                {out.suggestions.projects?.length > 0 && (
                                    <div className="p-5 bg-amber-50 dark:bg-amber-900/10 border border-amber-100 dark:border-amber-800/30 rounded-2xl">
                                        <p className="text-sm font-black uppercase tracking-widest text-amber-700 dark:text-amber-400 mb-3 flex items-center gap-2">
                                            <Lightbulb className="w-4 h-4" /> Portfolio Project Ideas
                                        </p>
                                        <ul className="space-y-2">
                                            {out.suggestions.projects.map((item: string, i: number) => (
                                                <li key={i} className="flex items-start gap-2 text-sm text-neutral-800 dark:text-neutral-200">
                                                    <span className="text-amber-400 mt-1 flex-shrink-0">•</span>{item}
                                                </li>
                                            ))}
                                        </ul>
                                    </div>
                                )}
                                {out.suggestions.career_tip && (
                                    <div className="p-5 bg-gradient-to-r from-indigo-50 to-purple-50 dark:from-indigo-900/20 dark:to-purple-900/20 border border-indigo-200 dark:border-indigo-700/40 rounded-2xl flex gap-4">
                                        <Lightbulb className="w-6 h-6 text-indigo-500 flex-shrink-0 mt-0.5" />
                                        <div>
                                            <p className="text-sm font-black uppercase tracking-widest text-indigo-600 dark:text-indigo-400 mb-2">💼 Strategic Career Tip</p>
                                            <p className="text-[15px] text-neutral-800 dark:text-neutral-200 leading-relaxed">{out.suggestions.career_tip}</p>
                                        </div>
                                    </div>
                                )}
                            </div>
                        )}
                    </div>
                )}

                {/* Find Jobs tab */}
                {activeTab === "jobs" && (
                    <JobsTab keywords={out.ats_keywords_used || []} jobTitle={jobTitle} />
                )}
            </div>

            {/* Footer: download all */}
            <div className="border-t border-neutral-200 dark:border-neutral-800 px-6 py-4 bg-neutral-50/50 dark:bg-neutral-900/30">
                <div className="flex items-center justify-between flex-wrap gap-3">
                    <p className="text-sm font-bold text-neutral-400">Download documents as PDF</p>
                    <div className="flex gap-2 flex-wrap">
                        {out.cover_letter && <PdfButton title="Cover_Letter" content={out.cover_letter} name={name} />}
                        {out.motivation_letter && <PdfButton title="Motivation_Letter" content={out.motivation_letter} name={name} />}
                        {out.application_text && <PdfButton title="Application_Email" content={out.application_text} name={name} />}
                    </div>
                </div>
            </div>
        </div>
    );
}

// ─────────────────────────────────────────────
// Job Search Tab
// ─────────────────────────────────────────────
function JobsTab({ keywords, jobTitle }: { keywords: string[]; jobTitle: string }) {
    const [role, setRole] = useState(jobTitle || "");
    const [location, setLocation] = useState("");

    const q = encodeURIComponent(`${role}${keywords.slice(0, 3).map(k => ` ${k}`).join("")}`);
    const loc = encodeURIComponent(location);

    const sources = [
        {
            name: "LinkedIn Jobs",
            icon: "💼",
            url: `https://www.linkedin.com/jobs/search/?keywords=${q}&location=${loc}`,
            color: "bg-blue-600 hover:bg-blue-700",
        },
        {
            name: "Indeed",
            icon: "🔍",
            url: `https://www.indeed.com/jobs?q=${q}&l=${loc}`,
            color: "bg-purple-600 hover:bg-purple-700",
        },
        {
            name: "Glassdoor",
            icon: "🏢",
            url: `https://www.glassdoor.com/Job/jobs.htm?sc.keyword=${q}&locT=C&locId=0`,
            color: "bg-green-600 hover:bg-green-700",
        },
        {
            name: "Adzuna",
            icon: "📋",
            url: `https://www.adzuna.com/search?q=${q}&where=${loc}`,
            color: "bg-orange-500 hover:bg-orange-600",
        },
        {
            name: "We Work Remotely",
            icon: "🌍",
            url: `https://weworkremotely.com/remote-jobs/search?term=${q}`,
            color: "bg-teal-600 hover:bg-teal-700",
        },
        {
            name: "Remote OK",
            icon: "🏠",
            url: `https://remoteok.com/remote-${encodeURIComponent(role.toLowerCase().replace(/\s+/g, "-"))}-jobs`,
            color: "bg-gray-700 hover:bg-gray-800",
        },
    ];

    return (
        <div className="space-y-5">
            <div>
                <h3 className="text-lg font-black text-neutral-900 dark:text-white mb-1">Find Jobs — Based on Your CV</h3>
                <p className="text-sm text-neutral-500">We pre-fill the search with your role and top ATS keywords. Adjust and open in the platform.</p>
            </div>

            {/* Filters */}
            <div className="grid sm:grid-cols-2 gap-4">
                <div>
                    <label className="text-xs font-black uppercase tracking-widest text-neutral-500 mb-1.5 block">Job Title / Role</label>
                    <input value={role} onChange={e => setRole(e.target.value)}
                        placeholder="e.g. Frontend Developer"
                        className="w-full bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700 rounded-xl px-4 py-2.5 text-sm text-neutral-900 dark:text-white focus:outline-none focus:border-indigo-400 transition" />
                </div>
                <div>
                    <label className="text-xs font-black uppercase tracking-widest text-neutral-500 mb-1.5 block">Location</label>
                    <input value={location} onChange={e => setLocation(e.target.value)}
                        placeholder="e.g. Vilnius, Lithuania"
                        className="w-full bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700 rounded-xl px-4 py-2.5 text-sm text-neutral-900 dark:text-white focus:outline-none focus:border-indigo-400 transition" />
                </div>
            </div>

            {/* Keywords being used */}
            {keywords.length > 0 && (
                <div>
                    <p className="text-xs font-bold text-neutral-400 mb-2">Keywords included in search:</p>
                    <div className="flex flex-wrap gap-1.5">
                        {keywords.slice(0, 6).map((kw, i) => (
                            <span key={i} className="px-2.5 py-1 bg-indigo-50 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-300 text-xs font-semibold rounded-full border border-indigo-200 dark:border-indigo-800">
                                {kw}
                            </span>
                        ))}
                    </div>
                </div>
            )}

            {/* Platform buttons */}
            <div className="grid sm:grid-cols-2 gap-3">
                {sources.map((s) => (
                    <a key={s.name} href={s.url} target="_blank" rel="noopener noreferrer"
                        className={`flex items-center gap-3 px-5 py-4 ${s.color} text-white rounded-2xl font-bold text-sm transition shadow-md hover:shadow-lg`}>
                        <span className="text-xl">{s.icon}</span>
                        <div>
                            <p className="font-black">{s.name}</p>
                            <p className="text-xs opacity-75 font-normal">Open and apply</p>
                        </div>
                        <ExternalLink className="w-4 h-4 ml-auto opacity-70" />
                    </a>
                ))}
            </div>

            <div className="p-4 bg-amber-50 dark:bg-amber-900/10 border border-amber-200 dark:border-amber-800/30 rounded-2xl text-sm text-amber-800 dark:text-amber-300">
                <strong>Tip:</strong> LinkedIn Jobs gives you the most relevant results. Log in first and use filters (Date Posted: Past Week, Experience Level) to find fresh listings.
            </div>
        </div>
    );
}
